/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#c9c4d8",
        "on-secondary-container": "#004d1b",
        "surface-bright": "#363940",
        "primary": "#c9bfff",
        "on-secondary-fixed": "#002108",
        "tertiary-container": "#c58300",
        "on-error-container": "#ffdad6",
        "on-primary": "#2e009c",
        "on-tertiary-container": "#3c2500",
        "secondary-fixed": "#69ff87",
        "inverse-primary": "#5d3fe0",
        "on-tertiary-fixed-variant": "#624000",
        "secondary-fixed-dim": "#3ce36a",
        "tertiary": "#ffb950",
        "error-container": "#93000a",
        "surface-container-highest": "#32353c",
        "on-background": "#e1e2eb",
        "surface-container-high": "#272a31",
        "on-primary-fixed": "#1a0063",
        "surface-container-lowest": "#0b0e14",
        "on-tertiary-fixed": "#291800",
        "on-secondary-fixed-variant": "#00531e",
        "on-primary-fixed-variant": "#441cc8",
        "surface-container-low": "#191c22",
        "surface-tint": "#c9bfff",
        "on-error": "#690005",
        "tertiary-fixed": "#ffddb3",
        "secondary-container": "#02c953",
        "primary-container": "#917eff",
        "primary-fixed": "#e5deff",
        "error": "#ffb4ab",
        "inverse-on-surface": "#2e3037",
        "surface-container": "#1d2026",
        "outline-variant": "#484555",
        "inverse-surface": "#e1e2eb",
        "surface-variant": "#32353c",
        "background": "#10131a",
        "surface-dim": "#10131a",
        "primary-fixed-dim": "#c9bfff",
        "on-surface": "#e1e2eb",
        "on-tertiary": "#452b00",
        "surface": "#10131a",
        "secondary": "#40e56c",
        "on-primary-container": "#28008a",
        "outline": "#928ea1",
        "tertiary-fixed-dim": "#ffb950",
        "on-secondary": "#003912"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "xl": "32px",
        "md": "16px",
        "margin-desktop": "40px",
        "lg": "24px",
        "sm": "8px",
        "margin-mobile": "16px",
        "gutter": "20px",
        "base": "4px"
      },
      fontFamily: {
        "body-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "code-sm": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
