"""
Scoring Rules Module for Cryptanium Trust Engine.
Implements modular, pluggable rules for calculating security score deductions.
"""

from abc import ABC, abstractmethod
from typing import List, Dict, Any
from backend.trust.severity import SeverityLevel, DEFAULT_SEVERITY_DEDUCTIONS
from backend.utils.parser import FindingItem


class ScoreDeductionResult:
    """Represents the deduction result generated by a single scoring rule."""
    def __init__(self, rule_name: str, deduction: float, reason: str, details: Dict[str, Any] = None):
        self.rule_name = rule_name
        self.deduction = round(max(0.0, deduction), 2)
        self.reason = reason
        self.details = details or {}

    def to_dict(self) -> Dict[str, Any]:
        return {
            "rule_name": self.rule_name,
            "deduction": self.deduction,
            "reason": self.reason,
            "details": self.details,
        }


class BaseScoringRule(ABC):
    """Abstract Base Class for all scoring rules (Open-Closed Principle)."""
    @abstractmethod
    def evaluate(self, findings: List[FindingItem]) -> ScoreDeductionResult:
        pass


class SeverityDeductionRule(BaseScoringRule):
    """Deducts points based on individual finding severities."""
    def __init__(self, deductions: Dict[SeverityLevel, float] = None):
        self.deductions = deductions or DEFAULT_SEVERITY_DEDUCTIONS

    def evaluate(self, findings: List[FindingItem]) -> ScoreDeductionResult:
        total_deduction = 0.0
        counts: Dict[str, int] = {sev.value: 0 for sev in SeverityLevel}

        for finding in findings:
            sev_enum = SeverityLevel.from_str(finding.severity)
            counts[sev_enum.value] += 1
            total_deduction += self.deductions.get(sev_enum, 0.0)

        reason = (
            f"Deducted {total_deduction:.1f} points across findings: "
            f"{counts['Critical']} Critical, {counts['High']} High, "
            f"{counts['Medium']} Medium, {counts['Low']} Low, {counts['Info']} Info"
        )
        return ScoreDeductionResult(
            rule_name="SeverityDeductionRule",
            deduction=total_deduction,
            reason=reason,
            details={"counts": counts, "deductions_applied": total_deduction},
        )


class SecretExposurePenaltyRule(BaseScoringRule):
    """Applies additional penalty for exposed secrets."""
    def __init__(self, penalty_per_secret: float = 15.0, max_penalty: float = 40.0):
        self.penalty_per_secret = penalty_per_secret
        self.max_penalty = max_penalty

    def evaluate(self, findings: List[FindingItem]) -> ScoreDeductionResult:
        secrets = [f for f in findings if f.is_secret]
        count = len(secrets)
        raw_penalty = count * self.penalty_per_secret
        penalty = min(raw_penalty, self.max_penalty)

        reason = (
            f"Detected {count} exposed secrets. Penalty: {penalty:.1f} pts"
            if count > 0
            else "No exposed secrets detected."
        )
        return ScoreDeductionResult(
            rule_name="SecretExposurePenaltyRule",
            deduction=penalty,
            reason=reason,
            details={"secrets_count": count, "penalty_per_secret": self.penalty_per_secret},
        )


class VulnerableDependencyPenaltyRule(BaseScoringRule):
    """Applies additional penalty for vulnerable dependencies."""
    def __init__(self, penalty_per_dep: float = 10.0, max_penalty: float = 30.0):
        self.penalty_per_dep = penalty_per_dep
        self.max_penalty = max_penalty

    def evaluate(self, findings: List[FindingItem]) -> ScoreDeductionResult:
        deps = [f for f in findings if f.is_dependency]
        count = len(deps)
        raw_penalty = count * self.penalty_per_dep
        penalty = min(raw_penalty, self.max_penalty)

        reason = (
            f"Detected {count} vulnerable dependencies. Penalty: {penalty:.1f} pts"
            if count > 0
            else "No vulnerable dependencies detected."
        )
        return ScoreDeductionResult(
            rule_name="VulnerableDependencyPenaltyRule",
            deduction=penalty,
            reason=reason,
            details={"vulnerable_deps_count": count, "penalty_per_dep": self.penalty_per_dep},
        )


class FindingVolumePenaltyRule(BaseScoringRule):
    """Applies scaling penalty if total number of findings exceeds threshold."""
    def __init__(self, threshold: int = 10, penalty_per_excess: float = 1.0, max_penalty: float = 20.0):
        self.threshold = threshold
        self.penalty_per_excess = penalty_per_excess
        self.max_penalty = max_penalty

    def evaluate(self, findings: List[FindingItem]) -> ScoreDeductionResult:
        total_count = len(findings)
        excess = max(0, total_count - self.threshold)
        raw_penalty = excess * self.penalty_per_excess
        penalty = min(raw_penalty, self.max_penalty)

        reason = (
            f"Total findings ({total_count}) exceeded threshold ({self.threshold}). "
            f"Volume penalty: {penalty:.1f} pts"
            if excess > 0
            else f"Total findings count ({total_count}) within normal threshold."
        )
        return ScoreDeductionResult(
            rule_name="FindingVolumePenaltyRule",
            deduction=penalty,
            reason=reason,
            details={"total_findings": total_count, "excess_findings": excess},
        )


class MissingDocumentationPenaltyRule(BaseScoringRule):
    """Future extension rule: Penalizes lack of security docs (e.g. SECURITY.md)."""
    def __init__(self, penalty: float = 5.0, doc_present: bool = True):
        self.penalty = penalty
        self.doc_present = doc_present

    def evaluate(self, findings: List[FindingItem]) -> ScoreDeductionResult:
        deduction = 0.0 if self.doc_present else self.penalty
        reason = "SECURITY.md present." if self.doc_present else f"Missing SECURITY.md documentation (-{self.penalty} pts)."
        return ScoreDeductionResult(
            rule_name="MissingDocumentationPenaltyRule",
            deduction=deduction,
            reason=reason,
            details={"doc_present": self.doc_present},
        )
